export type DomainErrorCode =
  | 'COMPETITION_NOT_EDITABLE'
  | 'COMPETITION_SCOPE_MISMATCH'
  | 'CONCURRENCY_CONFLICT'
  | 'DUPLICATE_PARTICIPANT'
  | 'DRAW_CONFIGURATION_FROZEN'
  | 'DRAW_CONFIGURATION_INCOMPATIBLE'
  | 'DRAW_CONFIGURATION_INTEGRITY_FAILURE'
  | 'DRAW_ANNULMENT_INVALID'
  | 'DRAW_AUTHORITY_INVALID'
  | 'DRAW_CONFIRMATION_INVALID'
  | 'DRAW_EVIDENCE_INVALID'
  | 'DRAW_EXECUTION_INVALID'
  | 'DRAW_SEED_INVALID'
  | 'GENERAL_AUTHORITY_INVALID'
  | 'GENERAL_CHAMPIONSHIP_STATE_INVALID'
  | 'GENERAL_CONTRIBUTION_INVALID'
  | 'GENERAL_FINALIZATION_INVALID'
  | 'GENERAL_PLACEMENT_INVALID'
  | 'GENERAL_SCORING_INVALID'
  | 'INVALID_COMPETITION_STATE'
  | 'INVALID_DISPLAY_NAME'
  | 'INVALID_GROUP_COUNT'
  | 'INVALID_PARTICIPANT_COUNT'
  | 'IDEMPOTENCY_CONFLICT'
  | 'IDEMPOTENCY_IN_PROGRESS'
  | 'LOCK_PRECONDITION_FAILED'
  | 'QUALIFICATION_AUTHORITY_INVALID'
  | 'QUALIFICATION_CONFIRMATION_INVALID'
  | 'QUALIFICATION_PROPOSAL_INVALID'
  | 'QUALIFICATION_TRANSITION_INVALID'
  | 'RULE_SET_FROZEN'
  | 'RULE_SET_INCOMPLETE'
  | 'RULE_SET_INCOMPATIBLE'
  | 'RULE_SET_INTEGRITY_FAILURE'
  | 'RESULT_ANNULMENT_INVALID'
  | 'RESULT_AUTHORITY_INVALID'
  | 'RESULT_CONFIRMATION_INVALID'
  | 'RESULT_DETAIL_INVALID'
  | 'TABLE_CALCULATION_INVALID'
  | 'TIE_UNRESOLVED'
  | 'TIE_BREAK_CRITERION_UNSUPPORTED';

export class DomainError extends Error {
  public readonly code: DomainErrorCode;

  public constructor(code: DomainErrorCode, message: string) {
    super(message);
    this.name = 'DomainError';
    this.code = code;
  }
}
